#ifndef SAE_S1_01_02_MAX_FIELDS_LENGTH_H
#define SAE_S1_01_02_MAX_FIELDS_LENGTH_H

#endif //SAE_S1_01_02_MAX_FIELDS_LENGTH_H


#define FILE_MAX_NAME_LENGTH 35
#define FILE_MAX_CITY_LENGTH 25
#define FILE_MAX_CODEPOSTAL_LENGTH 5
#define FILE_MAX_PHONE_LENGTH 14
#define FILE_MAX_EMAIL_LENGTH 70
#define FILE_MAX_PROFESSION_LENGTH 30

#define FILE_MAX_LINE_LENGTH FILE_MAX_NAME_LENGTH \
    + FILE_MAX_CITY_LENGTH                        \
    + FILE_MAX_CODEPOSTAL_LENGTH                  \
    + FILE_MAX_PHONE_LENGTH                       \
    + FILE_MAX_EMAIL_LENGTH                       \
    + FILE_MAX_PROFESSION_LENGTH

